Add Fluent function to Tera, link to data context
chevdor/tera-cli pull request #21
Opened 2023-02-16 21:25 UTC by alerque

Closes #20.

I'm not super happy with the ergonomics here. Part of the problem turned out to be the `fluent-template` crates resource loader wasn't quite as robust as hoped. Second there doesn't seem to be an easy way to make it cooperate with locales that don't have resource directories. We can fallback to a single FTL resource, but a directory still has to exist for any locales one attempts to use. Hence I didn't even include a way to pass a single file yet. I have an upstream issue open about that and am hoping to come up with a way to make this usable with just passing a single FTL file like one might pass a specific context file.

I don't think this will break any current usage at all.

2023-02-17 11:26 UTC, alerque commented
CI failures were because it was not being tested with features enabled, but it should be tested both with and without. I added the flag for `--all-features`, but I think the matrix needs to be extended to cover both cases.

2023-02-17 11:36 UTC, alerque commented
I expanded the test matrix to run the cargo test and check functions both with and without feature flags. I made the clippy one run just with all features because I don't think that will ever turn up more useful results with less features enabled. I also fixed an issue with the code when the feature is *not* enabled.

2023-04-22 12:04 UTC, alerque commented
Any chance on some feedback on this @chevdor I'm already using a custom build for some work that needs it, but keeping that up to date is a bit obnoxious, especially considering now I have to bump all the systems that got upgraded to the now-newer release version. If you don't plan on accepting this at least let me know so I can fork and move on. If you are still interested let me know what it needs to get merged an in a release.

2023-06-23 13:48 UTC, chevdor approved these changes

2023-06-23 13:48 UTC, chevdor commented
@alerque sorry for the time it took. Your update just landed when I took some time off and it then slipped out of my lists :)

2023-06-23 13:51 UTC, chevdor requested changes
`fast-fail` => `fail-fast` should work better :)

2023-06-23 13:52 UTC, chevdor commented on .github/workflows/quick-check.yml
> +      fast-fail: false
```suggestion
     fail-fast: false
```

2023-06-23 14:00 UTC, chevdor requested changes

2023-06-23 14:00 UTC, chevdor commented on .github/workflows/quick-check.yml
> +          command: test {{ matrix-feature-flags }}
```suggestion
          command: test ${{ matrix.feature-flags }}
```

2023-06-23 14:00 UTC, chevdor commented on .github/workflows/quick-check.yml
> +          command: check {{ matrix.feature-flags }}
```suggestion
          command: check ${{ matrix.feature-flags }}
```

2023-06-23 14:13 UTC, alerque commented
So sorry about the CI issues. I was wondering how I missed that, but the main reason is that it seems to be disabled on PRs except when they are first opened, and the CI changes were not added until later. You might consider dropping the `types:` limitation on the `pull_request:` trigger. Just a thought for later.

2023-06-23 14:23 UTC, chevdor commented
This is due to the fact that I need to approve the runs so they don't run immediately but they do.
It would be best/faster to test locally in your repo to ensure we have all the fixes. Some more fixes are required: you cannot pack command **and** args on a line.... so you need to split the 2.

2023-06-23 14:32 UTC, merged