Fix test commands
chevdor/tera-cli pull request #24
Opened 2023-06-23 11:40 UTC by KoltesDigital

The path was transformed twice, which seems not to be a problem on Linux, but it is on Windows.

```
thread 'cli_tests::basic::it_process_toml_to_stdout' panicked at 'called `Result::unwrap()` on an `Err` value: CargoError { cause: Some(NotFoundError { path: "XYZ\\tera-cli\\target\\debug\\tera.exe.exe" }) }', tests\test.rs:46:74
```

2023-06-23 13:36 UTC, chevdor commented
I don't think this PR is a good idea. We do **not** want to use `tera` in the tests but the local binary produced by the build.

2023-06-23 13:38 UTC, chevdor commented
That being said, I see your problem in `tera.exe.exe`. I don't have a windows machine but it sounds you do.
Could you test if using `CARGO_BIN_tera` works better on windows ?

2023-06-23 13:38 UTC, chevdor requested changes
The proposed fix is not good.
Try uninstalling tera from your system and running the tests...

2023-06-24 08:43 UTC, KoltesDigital commented
I think you've read too quickly. You used both `Command::cargo_bin` and `CARGO_BIN_EXE_xxx`, whose purpose is the same, and that's why there are two `.exe`. I've just removed the latter, so I'm still relying on `Command::cargo_bin("tera")` to result in `"XYZ\tera-cli\target\debug\\tera.exe"`. **It is not `Command::new("tera")`.** On the machine where I coded this PR I have no global `tera` in PATH.

I could have used `env!("CARGO_BIN_EXE_tera")` instead, it's supposed to work too, but I preferred the former because it explicitly calls `cargo_bin` so there's the semantics of an action going through `Cargo.toml`, whereas the env var is relying on some external deity to set up the environment beforehand. But that's debatable.

2023-06-24 09:58 UTC, chevdor approved these changes
Yes you are right indeed.

2023-06-24 09:58 UTC, merged